### ISSUE TITLE
Merging from another fork?

### ISSUE THREAD

**Issue by jonbell-lot23** [angrysql/hypertextual#4]
My repo got messed up on my desktop so I tried forking a brand new thing called Rodin. (named after the 5k CMS I wrote over a decade ago in PHP)

I made a couple of small tweaks to the views and added some CSS. Now I'm trying to learn how to make my changes into a pull request.

So whether or not you want my little design changes, do you know how to merge two repos?

**Comment by jmpavlick** [comment]
I have never personally done that, but it looks pretty easy - the top answer on [this StackOverflow post](http://stackoverflow.com/questions/13040958/merge-two-git-repositories-without-breaking-file-history) looks extremely promising.

But - since this is so small and I haven't changed anything other than the README since you made your changes, I think you could get away with cloning the hypertextual master repo and just over-writing what's there with your changes.

And sure, submit a pull request by all means! I'm interested to see what you've done.
